definitions:
  types.AuthenticateRequestBody:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  types.AuthenticateResponseBody:
    properties:
      user_id:
        type: string
    type: object
  types.CreateUserProfileRequestBody:
    properties:
      firstname:
        type: string
      lastname:
        type: string
      username:
        type: string
    required:
    - firstname
    - username
    type: object
  types.ErrorResponseBody:
    properties:
      error:
        type: string
    type: object
  types.GetTokensRequestBody:
    properties:
      code:
        type: integer
    required:
    - code
    type: object
  types.GetTokensResponseBody:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  types.RefreshRequestBody:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  types.RefreshResponseBody:
    properties:
      access_token:
        type: string
    type: object
  types.UpdateUserProfileRequestBody:
    properties:
      firstname:
        type: string
      lastname:
        type: string
      username:
        type: string
    required:
    - firstname
    - username
    type: object
  types.UserProfileResponseBody:
    properties:
      firstname:
        type: string
      lastname:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  title: Identity service
  version: "1.0"
paths:
  /auth/authenticate:
    post:
      consumes:
      - application/json
      description: Authenticates a user or creates a new user if one doesn't exist.
      parameters:
      - description: Authentication request body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/types.AuthenticateRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.AuthenticateResponseBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
      summary: Authenticate
      tags:
      - auth
  /auth/token:
    post:
      consumes:
      - application/json
      description: Gets access and refresh tokens.
      parameters:
      - description: Get tokens request body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/types.GetTokensRequestBody'
      - description: User ID (added on API gateway)
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: SHA-256 hash of device fingerprint
        in: header
        name: X-Device-Fingerprint
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetTokensResponseBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
      summary: GetTokens
      tags:
      - auth
  /auth/token/refresh:
    post:
      consumes:
      - application/json
      description: Refreshes access token.
      parameters:
      - description: Refresh request body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/types.RefreshRequestBody'
      - description: User ID (added on API gateway)
        in: header
        name: X-User-Id
        required: true
        type: string
      - description: SHA-256 hash of device fingerprint
        in: header
        name: X-Device-Fingerprint
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.RefreshResponseBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
      summary: Refresh
      tags:
      - auth
  /users/{user_id}/profile:
    get:
      consumes:
      - application/json
      description: Gets user profile information.
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: SHA-256 hash of device fingerprint
        in: header
        name: X-Device-Fingerprint
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.UserProfileResponseBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
      summary: GetUserProfile
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Updates user profile information.
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Update user profile request body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/types.UpdateUserProfileRequestBody'
      - description: SHA-256 hash of device fingerprint
        in: header
        name: X-Device-Fingerprint
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.UserProfileResponseBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
      summary: UpdateUserProfile
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Creates user profile information.
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Update user profile request body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/types.CreateUserProfileRequestBody'
      - description: SHA-256 hash of device fingerprint
        in: header
        name: X-Device-Fingerprint
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.UserProfileResponseBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.ErrorResponseBody'
      summary: CreateUserProfile
      tags:
      - users
swagger: "2.0"
